// #include <iostream>
// #include<conio.h>
// using namespace std;
// int main()
// {
//     int a,b;
    
//     cout<<"Enter values for a and b to calculate a/b"<<endl;
    
//     // cin>>a>>b;
//     a=10, b=0;

//     // try block activates exception handling
//     try 
//     {
//         if(b == 0)
//         {
//             // throw  exception
            
//             throw b;
            
            
//         }
        
//         else 
//         {
//         	cout<<endl<<"a/b = "<<a/b;
//         }
//     }
//     catch(int ) // catches exception
//     {
//         cout<<endl<<"Divide by zero Exception Caught: b = "<<b<<endl;
//     }
    
//     cout<<endl<<"END"<<endl;
    
//     return 0;
// }






